id: PBA3FC841
initial_creation_type: input
source_metadata:
  title: Jatsön Nyingpo Series
  language: bo
  description: 'Texts by and about the treasure-revealer Jatsön Nyingpo (’ja’ tshon
    snying po, 1585–1656), whose revelations include the famous Könchok Chidü (dkon
    mchog spyi ’dus) or ''Embodiment of the Three Jewels'':'
  volume:
    f6fc24305572416ebc484e4c5c4966c0:
      title: The Guidebook to the Hidden Land of Pemokö
      parent: Guidebooks
    a56bfc6af1b2473ba8eb77151e96bdd4:
      title: Maṇḍala Offering from the Tradition of Jatsön Nyingpo
      parent: Offering
    7cd16f98ac794d009331d34f48530c56:
      title: Prayer to Rigdzin Jatsön Nyingpo
      parent: Prayers
created_at: '2022-03-01T00:00:06.152472'
last_modified_at: '2022-03-01T00:00:06.152474'
